### ISSUE TITLE
Support development on non-Nitro machines

### ISSUE THREAD

**Issue by NullHypothesis** [brave-experiments/nitro-enclave-utils#2]
So far, the code can only be run on AWS Nitro enclaves, which is annoying to deal with. We should make it possible to develop the code on a non-Nitro machine, e.g., by disabling Nitro-specific calls.

**Comment by rillian** [comment]
I can think of three useful levels of support:

- disable nitro-specific calls in the application
- a mock version of the nitro-utils library which replies to calls with fake data without passing it through to nitro-specific hardware
- a mock version of the Nitro Security Module kernel device which can be used to test the whole app in qemu or a container.
