### ISSUE TITLE
How to use KMS in this framework?

### ISSUE THREAD

**Issue by RockOwl** [brave-experiments/nitro-enclave-utils#4]
Hello， I found this repository is useful,  It help me complete my project easier。 
But I don‘t know how to develop my project with aws-kms?   
Can you help me ?

**Comment by NullHypothesis** [comment]
I'm glad to hear that this project has been useful for you! :smiley:

Unfortunately, I cannot help with KMS and I currently have no plans to integrate this project with KMS, which is why I'm closing this issue.
